services:
  backend:
    build: .
    container_name: ai_documents
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
     - .:/app
    env_file:
      - .env
